// #define PID_KP 5.5
// #define PID_KD 2.5
// #define DEFAULT_SPEED 38
// #define MAX_SPEED 60
// #define TRUN_SPEED 47
// #define TRUN_BRAKE_SPEED 30
// #define TRUN_45_DEGREE_DURATION 320 // in milliseconds
// #define TRUN_90_DEGREE_DURATION 470 // in milliseconds

// #define PID_KI 0

// #define SENSOR_T_INTERSECTION_VALUE -8
// #define SENSOR_ALL_WHITE_VALUE -9

#define PID_KP 11
#define PID_KD 3
#define DEFAULT_SPEED 42
#define MAX_SPEED 200
#define TRUN_SPEED 43
#define TRUN_BRAKE_SPEED 30
#define TRUN_45_DEGREE_DURATION 320 // in milliseconds
#define TRUN_90_DEGREE_DURATION 400 // in milliseconds

#define BRAKE_SPEED 30
#define BRAKE_DURATION 40

#define PID_KI 0

#define SENSOR_T_INTERSECTION_VALUE -8
#define SENSOR_ALL_WHITE_VALUE -9

// gripper servo
#define PIN_SERVO_LEFT PIN_PB0
#define PIN_SERVO_RIGHT PIN_PE3
#define PIN_SERVO_VERTICAL PIN_PE2
#define SEFVO_MAX_PULSE 2200

#define SERVO_VERTICAL_UP_VALUE 120
#define SERVO_VERTICAL_DOWN_VALUE 40

#define SERVO_RIGHT_GRAB_VALUE 150
#define SERVO_LEFT_GRAB_VALUE 55

#define SERVO_RIGHT_RELEASE_VALUE 150
#define SERVO_LEFT_RELEASE_VALUE 55
